spring.application.name=readit
spring.datasource.url=jdbc:postgresql://readit_lymd_user:PCozgFXAsEHNGUU4gFuOz6gCKGqbtOBf@dpg-d6opsudm5p6s73degecg-a.oregon-postgres.render.com/readit_lymd
spring.datasource.username=readit_lymd_user
spring.datasource.password=PCozgFXAsEHNGUU4gFuOz6gCKGqbtOBf
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.format-sql=true


spring.jpa.open-in-view=false